// <auto-generated />
using System;
using JobsPulse.Storage.Storages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobsPulse.Storage.Migrations
{
    [DbContext(typeof(JobsPulseDbContext))]
    [Migration("20260809140000_AddSeenVacancyFilterHash")]
    partial class AddSeenVacancyFilterHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            #pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobsPulse.Storage.PersistentModels.PersistentBoardRegistryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BoardId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("board_id");

                    b.Property<string>("BoardUrl")
                        .HasColumnType("text")
                        .HasColumnName("board_url");

                    b.Property<DateTimeOffset>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovered_at");

                    b.Property<string>("DiscoveredVia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("discovered_via");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("JobCount")
                        .HasColumnType("integer")
                        .HasColumnName("job_count");

                    b.Property<DateTimeOffset?>("LastValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_validated_at");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.HasKey("Id")
                        .HasName("pk_board_registry");

                    b.HasIndex("SourceId", "BoardId")
                        .IsUnique()
                        .HasDatabaseName("ix_board_registry_source_id_board_id");

                    b.ToTable("board_registry", (string)null);
                });

            modelBuilder.Entity("JobsPulse.Storage.PersistentModels.PersistentCrawlIndexState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BoardsAdded")
                        .HasColumnType("integer")
                        .HasColumnName("boards_added");

                    b.Property<string>("CollectionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("collection_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<long>("RecordsSeen")
                        .HasColumnType("bigint")
                        .HasColumnName("records_seen");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.Property<int>("TokensFound")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_found");

                    b.HasKey("Id")
                        .HasName("pk_crawl_index_state");

                    b.HasIndex("SourceId", "CollectionId")
                        .IsUnique()
                        .HasDatabaseName("ix_crawl_index_state_source_id_collection_id");

                    b.ToTable("crawl_index_state", (string)null);
                });

            modelBuilder.Entity("JobsPulse.Storage.PersistentModels.PersistentOutboxItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<int>("ChangeKind")
                        .HasColumnType("integer")
                        .HasColumnName("change_kind");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dedup_key");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("VacancyPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("vacancy_payload");

                    b.HasKey("Id")
                        .HasName("pk_outbox");

                    b.HasIndex("DedupKey")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_dedup_key");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_status_next_attempt_at");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("JobsPulse.Storage.PersistentModels.PersistentSeenVacancy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BoardId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("board_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<string>("FilterHash")
                        .HasColumnType("text")
                        .HasColumnName("filter_hash");

                    b.Property<DateTimeOffset?>("FirstPublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_published_at");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("GroupId")
                        .HasColumnType("text")
                        .HasColumnName("group_id");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.PrimitiveCollection<string[]>("Offices")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("offices");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("post_id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_seen_vacancy");

                    b.HasIndex("SourceId", "BoardId")
                        .HasDatabaseName("ix_seen_vacancy_source_id_board_id")
                        .HasFilter("closed_at IS NULL");

                    b.HasIndex("SourceId", "BoardId", "PostId")
                        .IsUnique()
                        .HasDatabaseName("ix_seen_vacancy_source_id_board_id_post_id");

                    b.ToTable("seen_vacancy", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
